package com.yq.train.model;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated Mon Nov 04 21:14:31 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_name
     *
     * @mbg.generated Mon Nov 04 21:14:31 CST 2019
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_pwd
     *
     * @mbg.generated Mon Nov 04 21:14:31 CST 2019
     */
    private String adminPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.headportrait_url
     *
     * @mbg.generated Mon Nov 04 21:14:31 CST 2019
     */
    private String headportraitUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated Mon Nov 04 21:14:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated Mon Nov 04 21:14:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_name
     *
     * @return the value of admin.admin_name
     *
     * @mbg.generated Mon Nov 04 21:14:31 CST 2019
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_name
     *
     * @param adminName the value for admin.admin_name
     *
     * @mbg.generated Mon Nov 04 21:14:31 CST 2019
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_pwd
     *
     * @return the value of admin.admin_pwd
     *
     * @mbg.generated Mon Nov 04 21:14:31 CST 2019
     */
    public String getAdminPwd() {
        return adminPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_pwd
     *
     * @param adminPwd the value for admin.admin_pwd
     *
     * @mbg.generated Mon Nov 04 21:14:31 CST 2019
     */
    public void setAdminPwd(String adminPwd) {
        this.adminPwd = adminPwd == null ? null : adminPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.headportrait_url
     *
     * @return the value of admin.headportrait_url
     *
     * @mbg.generated Mon Nov 04 21:14:31 CST 2019
     */
    public String getHeadportraitUrl() {
        return headportraitUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.headportrait_url
     *
     * @param headportraitUrl the value for admin.headportrait_url
     *
     * @mbg.generated Mon Nov 04 21:14:31 CST 2019
     */
    public void setHeadportraitUrl(String headportraitUrl) {
        this.headportraitUrl = headportraitUrl == null ? null : headportraitUrl.trim();
    }
}