package com.yq.train.model;

public class ClassInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_info.student_id
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_info.teacher_id
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    private Integer teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_info.course_id
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_info.remnant_course
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    private Integer remnantCourse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_info.status
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_info.student_id
     *
     * @return the value of class_info.student_id
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_info.student_id
     *
     * @param studentId the value for class_info.student_id
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_info.teacher_id
     *
     * @return the value of class_info.teacher_id
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_info.teacher_id
     *
     * @param teacherId the value for class_info.teacher_id
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_info.course_id
     *
     * @return the value of class_info.course_id
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_info.course_id
     *
     * @param courseId the value for class_info.course_id
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_info.remnant_course
     *
     * @return the value of class_info.remnant_course
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    public Integer getRemnantCourse() {
        return remnantCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_info.remnant_course
     *
     * @param remnantCourse the value for class_info.remnant_course
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    public void setRemnantCourse(Integer remnantCourse) {
        this.remnantCourse = remnantCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_info.status
     *
     * @return the value of class_info.status
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_info.status
     *
     * @param status the value for class_info.status
     *
     * @mbg.generated Mon Nov 25 14:16:19 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}