package com.yq.train.model;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.class_hours
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    private Integer classHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.optional_number
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    private Integer optionalNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher_id
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    private Integer teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.description
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.class_hours
     *
     * @return the value of course.class_hours
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    public Integer getClassHours() {
        return classHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.class_hours
     *
     * @param classHours the value for course.class_hours
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    public void setClassHours(Integer classHours) {
        this.classHours = classHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.optional_number
     *
     * @return the value of course.optional_number
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    public Integer getOptionalNumber() {
        return optionalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.optional_number
     *
     * @param optionalNumber the value for course.optional_number
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    public void setOptionalNumber(Integer optionalNumber) {
        this.optionalNumber = optionalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher_id
     *
     * @return the value of course.teacher_id
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher_id
     *
     * @param teacherId the value for course.teacher_id
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.description
     *
     * @return the value of course.description
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.description
     *
     * @param description the value for course.description
     *
     * @mbg.generated Fri Nov 01 16:53:38 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}