package com.yq.train.model;

import java.util.Date;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.user_name
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.user_pwd
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.i_name
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    private String iName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tel
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    private Integer tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_describe
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    private String teacherDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.gmt_create
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.gmt_modified
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.course_total
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    private Integer courseTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.headportrait_url
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    private String headportraitUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.user_name
     *
     * @return the value of teacher.user_name
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.user_name
     *
     * @param userName the value for teacher.user_name
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.user_pwd
     *
     * @return the value of teacher.user_pwd
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.user_pwd
     *
     * @param userPwd the value for teacher.user_pwd
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.i_name
     *
     * @return the value of teacher.i_name
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public String getiName() {
        return iName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.i_name
     *
     * @param iName the value for teacher.i_name
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public void setiName(String iName) {
        this.iName = iName == null ? null : iName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tel
     *
     * @return the value of teacher.tel
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public Integer getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tel
     *
     * @param tel the value for teacher.tel
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public void setTel(Integer tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_describe
     *
     * @return the value of teacher.teacher_describe
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public String getTeacherDescribe() {
        return teacherDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_describe
     *
     * @param teacherDescribe the value for teacher.teacher_describe
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public void setTeacherDescribe(String teacherDescribe) {
        this.teacherDescribe = teacherDescribe == null ? null : teacherDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.gmt_create
     *
     * @return the value of teacher.gmt_create
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.gmt_create
     *
     * @param gmtCreate the value for teacher.gmt_create
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.gmt_modified
     *
     * @return the value of teacher.gmt_modified
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.gmt_modified
     *
     * @param gmtModified the value for teacher.gmt_modified
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.course_total
     *
     * @return the value of teacher.course_total
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public Integer getCourseTotal() {
        return courseTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.course_total
     *
     * @param courseTotal the value for teacher.course_total
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public void setCourseTotal(Integer courseTotal) {
        this.courseTotal = courseTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.headportrait_url
     *
     * @return the value of teacher.headportrait_url
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public String getHeadportraitUrl() {
        return headportraitUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.headportrait_url
     *
     * @param headportraitUrl the value for teacher.headportrait_url
     *
     * @mbg.generated Fri Nov 08 19:49:05 CST 2019
     */
    public void setHeadportraitUrl(String headportraitUrl) {
        this.headportraitUrl = headportraitUrl == null ? null : headportraitUrl.trim();
    }
}