package com.yq.train.mapper;

import com.yq.train.model.ClassInfo;
import com.yq.train.model.ClassInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ClassInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_info
     *
     * @mbg.generated Sun Dec 01 13:48:12 CST 2019
     */
    long countByExample(ClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_info
     *
     * @mbg.generated Sun Dec 01 13:48:12 CST 2019
     */
    int deleteByExample(ClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_info
     *
     * @mbg.generated Sun Dec 01 13:48:12 CST 2019
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_info
     *
     * @mbg.generated Sun Dec 01 13:48:12 CST 2019
     */
    int insert(ClassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_info
     *
     * @mbg.generated Sun Dec 01 13:48:12 CST 2019
     */
    int insertSelective(ClassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_info
     *
     * @mbg.generated Sun Dec 01 13:48:12 CST 2019
     */
    List<ClassInfo> selectByExampleWithRowbounds(ClassInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_info
     *
     * @mbg.generated Sun Dec 01 13:48:12 CST 2019
     */
    List<ClassInfo> selectByExample(ClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_info
     *
     * @mbg.generated Sun Dec 01 13:48:12 CST 2019
     */
    ClassInfo selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_info
     *
     * @mbg.generated Sun Dec 01 13:48:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") ClassInfo record, @Param("example") ClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_info
     *
     * @mbg.generated Sun Dec 01 13:48:12 CST 2019
     */
    int updateByExample(@Param("record") ClassInfo record, @Param("example") ClassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_info
     *
     * @mbg.generated Sun Dec 01 13:48:12 CST 2019
     */
    int updateByPrimaryKeySelective(ClassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_info
     *
     * @mbg.generated Sun Dec 01 13:48:12 CST 2019
     */
    int updateByPrimaryKey(ClassInfo record);
}